# Memory System Configuration
# Settings for persistent memory, embeddings, and search

# =============================================================================
# Embedding Settings
# =============================================================================
embeddings:
  # Model for generating embeddings
  model: "text-embedding-3-small"

  # Embedding dimensions (model-specific)
  dimensions: 1536

  # Batch size for bulk embedding operations
  batch_size: 100

  # Rate limit for embedding API calls
  requests_per_minute: 500

  # Cache embeddings locally
  cache_enabled: true

# =============================================================================
# Search Settings
# =============================================================================
search:
  # Default search type: keyword, semantic, hybrid
  default_type: "hybrid"

  # Number of results to return
  default_limit: 10

  # Similarity threshold for semantic search (0-1)
  similarity_threshold: 0.7

  # Hybrid search weights
  hybrid:
    keyword_weight: 0.3
    semantic_weight: 0.7

  # Boost recent entries in results
  recency_boost: true
  recency_decay_days: 30

# =============================================================================
# Retention Settings
# =============================================================================
retention:
  # How long to keep different entry types (days, 0 = forever)
  by_type:
    fact: 0           # Keep forever
    preference: 0     # Keep forever
    insight: 0        # Keep forever
    relationship: 0   # Keep forever
    event: 90         # 90 days
    task: 30          # 30 days

  # Minimum importance to keep permanently
  permanent_importance_threshold: 8

  # Archive instead of delete expired entries
  archive_expired: true

  # Days before archiving inactive entries
  inactive_archive_days: 180

# =============================================================================
# Sync Settings
# =============================================================================
sync:
  # Sync memory entries to MEMORY.md
  md_sync_enabled: true

  # Only sync entries above this importance
  md_sync_importance_threshold: 7

  # Sync daily logs to memory/logs/
  daily_logs_enabled: true

  # Consolidate related memories periodically
  consolidation_enabled: true
  consolidation_interval_hours: 24

# =============================================================================
# Access Tracking
# =============================================================================
access:
  # Log memory access for analytics
  logging_enabled: true

  # Track which entries are most accessed
  track_popularity: true

  # Decay old access counts over time
  access_decay_enabled: true
  access_decay_half_life_days: 30

# =============================================================================
# Deduplication
# =============================================================================
deduplication:
  # Enable content hash deduplication
  enabled: true

  # Similarity threshold for near-duplicate detection
  similarity_threshold: 0.95

  # Action for duplicates: reject, merge, flag
  duplicate_action: "reject"

# =============================================================================
# Limits
# =============================================================================
limits:
  # Maximum content length (characters)
  max_content_length: 10000

  # Maximum tags per entry
  max_tags: 20

  # Maximum entries per day
  max_entries_per_day: 500

  # Maximum total entries (0 = unlimited)
  max_total_entries: 0
