# Memory System Configuration
# Settings for persistent memory, embeddings, and search
#
# DexAI supports multiple memory backends with cloud and self-hosted options.
# See goals/memory_providers_design.md for architecture details.
#
# Provider Options:
#   - native: Local SQLite + hybrid search (default, no dependencies)
#   - mem0: Mem0 cloud or self-hosted (graph memory, 24+ vector DBs)
#   - zep: Zep cloud or self-hosted (temporal knowledge graph)
#   - simplemem: SimpleMem cloud (semantic compression, 30x fewer tokens)
#   - claudemem: ClaudeMem local (progressive disclosure, auto-capture)

# =============================================================================
# Provider Configuration
# =============================================================================
provider:
  # Active provider
  active: "native"  # Options: native, mem0, zep, simplemem, claudemem

  # ─────────────────────────────────────────────────────────────────────────
  # Native Provider (LOCAL mode only)
  # No external dependencies - uses local SQLite + OpenAI embeddings
  # ─────────────────────────────────────────────────────────────────────────
  native:
    database_path: "data/memory.db"
    context_database_path: "data/context.db"
    # Uses embedding settings below

  # ─────────────────────────────────────────────────────────────────────────
  # Mem0 Provider (CLOUD or SELF_HOSTED mode)
  # Cloud: app.mem0.ai - no infrastructure needed
  # Self-hosted: requires vector store (Qdrant, Chroma, etc.)
  # ─────────────────────────────────────────────────────────────────────────
  mem0:
    # Deployment mode: "cloud" or "self_hosted"
    mode: "cloud"

    # Cloud mode configuration
    cloud:
      api_key: "${MEM0_API_KEY}"
      org_id: "${MEM0_ORG_ID}"
      project_id: "${MEM0_PROJECT_ID}"

    # Self-hosted mode configuration
    self_hosted:
      vector_store:
        provider: "qdrant"
        config:
          host: "localhost"
          port: 6333
      embedder:
        provider: "openai"
        model: "text-embedding-3-small"
      llm:
        provider: "anthropic"
        model: "claude-sonnet-4-20250514"

  # ─────────────────────────────────────────────────────────────────────────
  # Zep Provider (CLOUD or SELF_HOSTED mode)
  # Cloud: getzep.com - managed service, <200ms latency
  # Self-hosted: requires Neo4j + OpenSearch
  # ─────────────────────────────────────────────────────────────────────────
  zep:
    mode: "cloud"
    cloud:
      api_key: "${ZEP_API_KEY}"
      project_id: "${ZEP_PROJECT_ID}"
    self_hosted:
      api_url: "http://localhost:8000"
      api_key: "${ZEP_SELF_HOSTED_API_KEY}"

  # ─────────────────────────────────────────────────────────────────────────
  # SimpleMem Provider (CLOUD mode only)
  # Features: semantic compression, 30x fewer tokens, +26% F1
  # ─────────────────────────────────────────────────────────────────────────
  simplemem:
    api_url: "https://mcp.simplemem.cloud"
    api_key: "${SIMPLEMEM_API_KEY}"
    user_id: "${SIMPLEMEM_USER_ID}"

  # ─────────────────────────────────────────────────────────────────────────
  # ClaudeMem Provider (LOCAL mode only)
  # Source: https://github.com/thedotmack/claude-mem
  # Requires: Node.js 18+, Bun
  # ─────────────────────────────────────────────────────────────────────────
  claudemem:
    data_dir: "~/.claude-mem"
    worker_port: 37777
    auto_capture:
      enabled: true
      session_start: true
      post_tool_use: true
      session_end: true

# =============================================================================
# Fallback Configuration
# =============================================================================
fallback:
  enabled: true
  provider: "native"
  log_fallback: true
  retry_primary_after: 300
  max_failures: 3

# =============================================================================
# ADHD-specific Settings (applied regardless of provider)
# =============================================================================
adhd:
  language_filter: true
  forward_facing: true
  max_context_injection: 5
  reminder_style: "gentle"
  context_stale_hours: 168

# =============================================================================
# Embedding Settings
# =============================================================================
embeddings:
  # Model for generating embeddings
  model: "text-embedding-3-small"

  # Embedding dimensions (model-specific)
  dimensions: 1536

  # Batch size for bulk embedding operations
  batch_size: 100

  # Rate limit for embedding API calls
  requests_per_minute: 500

  # Cache embeddings locally
  cache_enabled: true

# =============================================================================
# Search Settings
# =============================================================================
search:
  # Default search type: keyword, semantic, hybrid
  default_type: "hybrid"

  # Number of results to return
  default_limit: 10

  # Similarity threshold for semantic search (0-1)
  similarity_threshold: 0.7

  # Hybrid search weights
  hybrid:
    keyword_weight: 0.3
    semantic_weight: 0.7

  # Boost recent entries in results
  recency_boost: true
  recency_decay_days: 30

# =============================================================================
# Retention Settings
# =============================================================================
retention:
  # How long to keep different entry types (days, 0 = forever)
  by_type:
    fact: 0           # Keep forever
    preference: 0     # Keep forever
    insight: 0        # Keep forever
    relationship: 0   # Keep forever
    event: 90         # 90 days
    task: 30          # 30 days

  # Minimum importance to keep permanently
  permanent_importance_threshold: 8

  # Archive instead of delete expired entries
  archive_expired: true

  # Days before archiving inactive entries
  inactive_archive_days: 180

# =============================================================================
# Sync Settings
# =============================================================================
sync:
  # Sync memory entries to MEMORY.md
  md_sync_enabled: true

  # Only sync entries above this importance
  md_sync_importance_threshold: 7

  # Sync daily logs to memory/logs/
  daily_logs_enabled: true

  # Consolidate related memories periodically
  consolidation_enabled: true
  consolidation_interval_hours: 24

# =============================================================================
# Access Tracking
# =============================================================================
access:
  # Log memory access for analytics
  logging_enabled: true

  # Track which entries are most accessed
  track_popularity: true

  # Decay old access counts over time
  access_decay_enabled: true
  access_decay_half_life_days: 30

# =============================================================================
# Deduplication
# =============================================================================
deduplication:
  # Enable content hash deduplication
  enabled: true

  # Similarity threshold for near-duplicate detection
  similarity_threshold: 0.95

  # Action for duplicates: reject, merge, flag
  duplicate_action: "reject"

# =============================================================================
# Limits
# =============================================================================
limits:
  # Maximum content length (characters)
  max_content_length: 10000

  # Maximum tags per entry
  max_tags: 20

  # Maximum entries per day
  max_entries_per_day: 500

  # Maximum total entries (0 = unlimited)
  max_total_entries: 0
