# Mobile Push Notification Configuration
# Phase 10a: Web Push + PWA

# VAPID (Voluntary Application Server Identification)
# Used for Web Push authentication
vapid:
  # Generate keys with: python -m tools.mobile.push.web_push generate-keys
  # Store keys in environment variables (NOT in this file):
  #   VAPID_PUBLIC_KEY=<public_key>
  #   VAPID_PRIVATE_KEY=<private_key>
  public_key: ""   # Set via VAPID_PUBLIC_KEY env var
  private_key: ""  # Set via VAPID_PRIVATE_KEY env var
  subject: "mailto:notifications@dexai.app"

# Default settings for new users
defaults:
  # Rate limiting (ADHD-specific: prevents notification fatigue)
  max_notifications_per_hour: 6
  cooldown_after_burst_minutes: 30

  # Batching (groups related notifications)
  batch_window_seconds: 300  # 5 minutes
  max_batch_size: 10

  # Flow protection (respect hyperfocus states)
  respect_flow_state: true
  flow_interrupt_threshold: 8  # Priority 8+ can interrupt flow

  # Quiet hours (automatic DND)
  default_quiet_hours:
    start: "22:00"
    end: "08:00"
    timezone: "local"  # Uses user's timezone

# Notification categories with defaults
categories:
  task_reminder:
    name: "Task Reminder"
    description: "Reminders about upcoming or pending tasks"
    default_priority: 6
    can_batch: true
    can_suppress: true
    icon: "task"
    color: "#4F46E5"  # Indigo

  commitment_due:
    name: "Commitment Due"
    description: "Important deadlines and commitments"
    default_priority: 8
    can_batch: false
    can_suppress: false  # Always deliver - these are important
    icon: "commitment"
    color: "#DC2626"  # Red

  message_received:
    name: "Message Received"
    description: "New messages from connected channels"
    default_priority: 5
    can_batch: true
    can_suppress: true
    icon: "message"
    color: "#059669"  # Green

  flow_state_ended:
    name: "Flow State Ended"
    description: "Notification when focus session completes"
    default_priority: 4
    can_batch: false
    can_suppress: false  # User wants to know when flow ends
    icon: "flow"
    color: "#8B5CF6"  # Purple

  daily_summary:
    name: "Daily Summary"
    description: "Daily progress and upcoming tasks summary"
    default_priority: 3
    can_batch: false
    can_suppress: true
    icon: "summary"
    color: "#6B7280"  # Gray

# ADHD-specific settings
adhd:
  # Notification language
  use_supportive_language: true
  avoid_guilt_phrases: true

  # Examples of phrases to avoid:
  # - "You missed..."
  # - "Overdue"
  # - "You forgot..."
  # - "You should have..."

  # Examples of supportive alternatives:
  # - "Ready when you are"
  # - "Waiting for you"
  # - "Still available"
  # - "Your next step"

  # Timing protection
  transition_buffer_minutes: 5  # Don't notify right after task switch

  # Content guidelines
  max_title_length: 50
  max_body_length: 100
  include_single_action: true  # Each notification has ONE clear action

# Web Push settings
web_push:
  # Time to live for push messages (in seconds)
  default_ttl: 86400  # 24 hours

  # Retry settings
  max_retries: 3
  retry_delay_seconds: 1
  retry_backoff_multiplier: 2

  # Cleanup
  prune_inactive_subscriptions_days: 30

# Queue processing
queue:
  # How often to process the queue (in seconds)
  process_interval: 30

  # Maximum notifications to process per run
  batch_size: 100

  # Expired notification handling
  expire_after_hours: 24

# Analytics
analytics:
  # Data retention
  retain_delivery_logs_days: 90

  # Metrics collection
  track_delivery_rate: true
  track_click_rate: true
  track_dismiss_rate: true

# =============================================================================
# Phase 10c: Native Enhancements
# =============================================================================

native:
  # Home screen widgets
  widgets:
    enabled: true
    refresh_interval_minutes: 60
    sizes:
      - small
      - medium
    display:
      show_energy: true
      show_upcoming_count: true
      show_step_progress: true
      compact_mode: false
      max_title_length: 40
      max_body_length: 80
    theme:
      light:
        background: "#FFFFFF"
        text: "#111827"
        text_secondary: "#6B7280"
        accent: "#4F46E5"
      dark:
        background: "#1F2937"
        text: "#F9FAFB"
        text_secondary: "#9CA3AF"
        accent: "#818CF8"

  # Apple Watch integration
  watch:
    enabled: true
    complications:
      - current_task  # Shows current task title
      - next_reminder # Shows next reminder time
      - task_count    # Shows remaining task count
      - energy_level  # Shows current energy level
    sync_interval_seconds: 300
    max_title_length: 30
    max_step_length: 50

  # Siri Shortcuts
  shortcuts:
    enabled: true
    suggested_limit: 5
    available_shortcuts:
      - id: next_task
        title: "Next Task"
        phrase: "What's my next task?"
        description: "Ask Dex what to work on next"
        icon: checklist
      - id: start_task
        title: "Start Task"
        phrase: "I'm starting a task"
        description: "Tell Dex you are starting your next task"
        icon: play.fill
      - id: complete_step
        title: "Complete Step"
        phrase: "I finished a step"
        description: "Mark the current step as done"
        icon: checkmark.circle.fill
      - id: snooze_reminders
        title: "Snooze Reminders"
        phrase: "Snooze my reminders"
        description: "Snooze all reminders for 30 minutes"
        icon: bell.slash
        default_duration_minutes: 30
      - id: start_focus
        title: "Start Focus"
        phrase: "Start focus mode"
        description: "Enter focus mode with DND"
        icon: scope
        default_duration_minutes: 25
      - id: end_focus
        title: "End Focus"
        phrase: "End focus mode"
        description: "Exit focus mode"
        icon: hand.raised
      - id: check_in
        title: "Check In"
        phrase: "Check in with Dex"
        description: "Quick status check and guidance"
        icon: person.wave.2
      - id: add_task
        title: "Add Task"
        phrase: "Add a task"
        description: "Quickly add a new task"
        icon: plus.circle.fill

  # 3D Touch / Long Press Quick Actions
  quick_actions:
    enabled: true
    items:
      - id: next_task
        title: "Next Task"
        subtitle: "See what to do next"
        icon: task
      - id: quick_capture
        title: "Quick Capture"
        subtitle: "Add a task"
        icon: add
      - id: focus_mode
        title: "Focus Mode"
        subtitle: "Start focusing"
        icon: focus
    dynamic_actions:
      enabled: true
      max_count: 1
      include_recent_task: true

  # Enhanced Background Sync
  background_sync:
    enabled: true
    min_interval_minutes: 15
    sync_on_network_change: true
    data_types:
      - tasks
      - preferences
      - notifications
    offline_queue:
      enabled: true
      max_queue_size: 100
      max_retry_count: 5
      retry_delay_base_ms: 1000
      conflict_resolution: "server_wins"  # or "client_wins", "manual"
